version: '3.7'

services:

  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: reservation
      POSTGRES_USER: rental
      POSTGRES_PASSWORD: u_e_sij489sakijdsafidjf
    ports:
      - 5432:5432
    network_mode: host
    volumes:
      - ./car_reservation/data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./car_reservation/data:/var/lib/postgresql/data
      - ./servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev
      - PGADMIN_DEFAULT_PASSWORD=dev
      - PGADMIN_LISTEN_PORT=8089
    network_mode: "host"
